# Copied from upstream Ruby extension https://github.com/zed-extensions/ruby/tree/784b0cbd31a46a453f6c24d2f9dae6eda86f4ac2/languages/ruby

name = "Ruby"
grammar = "ruby"
path_suffixes = [
  "rb",
  "Gemfile",
  "Guardfile",
  "rake",
  "Rakefile",
  "ru",
  "thor",
  "cap",
  "capfile",
  "Capfile",
  "jbuilder",
  "rabl",
  "rxml",
  "builder",
  "gemspec",
  "rdoc",
  "thor",
  "pryrc",
  "simplecov",
  "Steepfile",
  "Podfile",
  "Brewfile",
  "Vagrantfile",
  "Puppetfile",
]
first_line_pattern = '^#!.*\bruby\b'
line_comments = ["# "]
autoclose_before = ";:.,=}])>"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = [
    "comment",
    "string",
  ] },
  { start = "'", end = "'", close = true, newline = false, not_in = [
    "comment",
    "string",
  ] },
]
collapsed_placeholder = "# ..."
tab_size = 2
scope_opt_in_language_servers = ["tailwindcss-language-server"]

[overrides.string]
word_characters = ["-"]
opt_into_language_servers = ["tailwindcss-language-server"]
